; Script generated by the HM NIS Edit Script Wizard.

Outfile "SearchToolInstaller.exe"
InstallDir $PROGRAMFILES\SearchTool
RequestExecutionLevel user

Page components
Page directory
Page instfiles

Section
SetOutPath $INSTDIR
File /r "dist\*.*"
SectionEnd

Section "CreateStartMenuShortcuts"
  SetShellVarContext current
  CreateDirectory "$SMPROGRAMS\SearchTool"
  CreateShortCut "$SMPROGRAMS\SearchTool\SearchTool.lnk" "$INSTDIR\searchtool.exe"
SectionEnd
